//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    
    public partial class ComprasProveedor_Result1
    {
        public int idCompra { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> adeuda { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
    }
}
