//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoBeneficio
    {
        public int idCostoBeneficio { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> idCompra { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string EstadoCuenta { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
