//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egreso()
        {
            this.AbonoEgreso = new HashSet<AbonoEgreso>();
        }
    
        public int idEgreso { get; set; }
        public short idConcepto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public string EstadoCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonoEgreso> AbonoEgreso { get; set; }
        public virtual Concepto Concepto { get; set; }
    }
}
