//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumo()
        {
            this.Compra_Insumo = new HashSet<Compra_Insumo>();
            this.LaborLote_Insumo = new HashSet<LaborLote_Insumo>();
        }
    
        public short idInsumo { get; set; }
        public Nullable<byte> idTipoInsumo { get; set; }
        public string NombreInsumo { get; set; }
        public string Descripcion { get; set; }
        public decimal CantidadExistente { get; set; }
        public string Marca { get; set; }
        public string UnidadMedida { get; set; }
        public string EstadoInsumo { get; set; }
        public Nullable<int> PrecioPromedio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Insumo> Compra_Insumo { get; set; }
        public virtual TipoInsumo TipoInsumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaborLote_Insumo> LaborLote_Insumo { get; set; }
    }
}
