//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labor()
        {
            this.Labor_Lote = new HashSet<Labor_Lote>();
        }
    
        public short idLabor { get; set; }
        public string NombreLabor { get; set; }
        public bool ModificaArboles { get; set; }
        public bool RequiereInsumo { get; set; }
        public string Descripcion { get; set; }
        public string EstadoLabor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Labor_Lote> Labor_Lote { get; set; }
    }
}
