//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborLote_Insumo
    {
        public int id { get; set; }
        public int idLabor_Lote { get; set; }
        public short idInsumo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual Labor_Lote Labor_Lote { get; set; }
    }
}
