//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor_Lote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labor_Lote()
        {
            this.LaborLote_Insumo = new HashSet<LaborLote_Insumo>();
            this.SalarioPersonaTemporal = new HashSet<SalarioPersonaTemporal>();
        }
    
        public int idLabor_Lote { get; set; }
        public short idLabor { get; set; }
        public short idLote { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Labor Labor { get; set; }
        public virtual Lote Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaborLote_Insumo> LaborLote_Insumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarioPersonaTemporal> SalarioPersonaTemporal { get; set; }
    }
}
