//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoProduccion
    {
        public int id { get; set; }
        public int idProduccion { get; set; }
        public int idVenta { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Produccion Produccion { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
