//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPago_DeudaPersona
    {
        public int idRegistroPago_DeudaPersona { get; set; }
        public int idRegistroPago { get; set; }
        public int idDeudaPersona { get; set; }
    
        public virtual DeudaPersona DeudaPersona { get; set; }
        public virtual RegistroPago RegistroPago { get; set; }
    }
}
