//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPagoSalario
    {
        public int idRegistroPagoSalario { get; set; }
        public int idRegistroPago { get; set; }
        public Nullable<int> idSalarioPersonaTemporal { get; set; }
        public Nullable<int> idSalarioPersonaPermanente { get; set; }
    
        public virtual RegistroPago RegistroPago { get; set; }
        public virtual SalarioPersonaTemporal SalarioPersonaTemporal { get; set; }
        public virtual SalarioPersonaPermanente SalarioPersonaPermanente { get; set; }
    }
}
