//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarioPersonaTemporal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalarioPersonaTemporal()
        {
            this.RegistroPagoSalario = new HashSet<RegistroPagoSalario>();
        }
    
        public int idSalarioPersonaTemporal { get; set; }
        public string DocumentoPersona { get; set; }
        public int idLabor_Lote { get; set; }
        public int Cantidad { get; set; }
        public decimal Valor { get; set; }
        public string EstadoCuenta { get; set; }
    
        public virtual Labor_Lote Labor_Lote { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroPagoSalario> RegistroPagoSalario { get; set; }
    }
}
