//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public short idUsuario { get; set; }
        public string Nickname { get; set; }
        public string Rol { get; set; }
        public string Contrasena { get; set; }
        public string PreguntaSeguridad { get; set; }
        public string Respuesta { get; set; }
        public string EstadoUsuario { get; set; }
    }
}
